spring:
    application:
        name: Profile Service

    security:
        user:
            name: prospyr_profile
            password: prospyr_profile

jwt:
    private-key: classpath:jwt/app.key
    public-key: classpath:jwt/app.pub
    ttl: 15m